# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d0107cbc01b2f8ce6341c50ca97b2ebb8825f9bc524e4df23763e128e5f7a3139424f708dff313ba7984ee0c80002f41289a575757f268ec99571eba1d34ea9

test:
  secret_key_base: c3540feaf23df81d06f08114a6848c7df9a9a6848a66ea29368315e74dbd35024a362cfb1bda8a65253c6afa37e7ba138f09e1db1f5fb6c0256520c6c0b16d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
